spring:
  application:
    name: student-result

server:
  port: 8081

student:
  api:
    base-url: http://software.diu.edu.bd:8006
    semester-info-end-point: /result/semesterList
    student-info-end-point: /result/studentInfo